server:
  port: 8101

spring:
  application:
    name: hello-client

service:
  hello:
    url: http://HELLO-SERVICE/hello

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/